"""
-*- coding: utf-8 -*-
@Time    : 2025-04-23
@Github  : windbell0711/BingGo
@Author  : windbell07
@License : Apache 2.0
@File    : gists.py
partly generated by deepseek.
"""
import requests
import time
import config

# 配置参数
GIST_ID = config.B_GISTS_ID
ACCESS_TOKEN = config.B_GISTS_ACCESS
FILENAME = "gistfile1.txt"  # 代码片段文件名
API_URL = f"https://gitee.com/api/v5/gists/{GIST_ID}"

def get_message():
    """获取最新消息"""
    params = {"access_token": ACCESS_TOKEN}
    try:
        response = requests.get(API_URL, params=params)
        if response.status_code == 200:
            files = response.json()["files"]
            current_content = files.get(FILENAME, {}).get("content", "")
            return current_content
        else:
            print(f"获取失败，状态码：{response.status_code}")
    except Exception as e:
        print(f"网络错误：{str(e)}")
    return None

def update_message(new_msg):
    """更新消息"""
    payload = {
        "access_token": ACCESS_TOKEN,
        "files": {
            FILENAME: {
                "content": new_msg
            }
        }
    }
    try:
        response = requests.patch(API_URL, json=payload)
        if response.status_code == 200:
            return True
        print(f"更新失败，状态码：{response.status_code}")
    except Exception as e:
        print(f"网络错误：{str(e)}")
    return False

def receive(username: str) -> str:
    """接收消息"""
    cnt = 0
    while True:
        msg = get_message()
        if msg and not msg.startswith(username + ":"):
            print(f"\n[对方] {msg}")
            return msg
        if cnt > 5:
            time.sleep(10)  # 每隔10秒检查一次消息，不可太快，有api访问限制
        time.sleep(2.5)  # 前5次快一些检查
        cnt += 1

def send(username: str, msg: str):
    """发送消息"""
    if update_message(f"{username}: {msg}"):
        print("✓ 发送成功")
        return True
    print("✗ 发送失败")
    return False


if __name__ == "__main__":
    username = input("请输入你的昵称：")
    print(f"聊天室已启动 | 你的昵称：[{username}]")
    while True:
        receive(username)
        send(username, msg=input("[你] "))
